# Generated by Django 3.0 on 2020-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='otp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='otp_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
