# Generated by Django 3.0 on 2020-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ipadress',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.TextField(default=True),
        ),
    ]
