# Generated by Django 3.0 on 2020-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200622_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
