# Generated by Django 3.0 on 2020-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200629_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ipadress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
